{
  "toughnessValueEnderiumArmor": 200,
  "enchantmentValueEnderiumArmor": 85,
  "knockbackResistanceValueEnderiumArmor": 3,
  "protectionValueEnderiumBoots": 30,
  "protectionValueEnderiumLeggings": 50,
  "protectionValueEnderiumChestplate": 70,
  "protectionValueEnderiumHelmet": 30,
  "speedIIIEnderiumArmor": true,
  "jumpIIIEnderiumArmor": true,
  "nightVisionEnderiumArmor": true,
  "fireResistanceEnderiumArmor": true,
  "immuneToFallDamageEnderiumArmor": true,
  "canFlyEnderiumArmor": true,
  "neverLoseHungerEnderiumArmor": true,
  "canWalkOnPowderedSnowEnderium": true,
  "makesPiglinsNeutralEnderium": true,
  "endermanWillNotBeAngryWithYouEnderium": true,
  "speedEnderiumTier": 130,
  "enchantmentValueEnderiumBow": 5,
  "damageEnderiumBow": 14,
  "attackDamageBonusEnderiumTier": 40,
  "enchantmentValueEnderiumTier": 85,
  "attackDamageEnderiumPickaxe": 18,
  "attackSpeedEnderiumPickaxe": 2.0,
  "attackDamageEnderiumAxe": 20,
  "attackSpeedEnderiumAxe": 2.0,
  "attackDamageEnderiumShovel": 17,
  "attackSpeedEnderiumShovel": 2.0,
  "attackDamageEnderiumSword": 22,
  "attackSpeedEnderiumSword": 2.0,
  "attackDamageEnderiumHoe": 14,
  "attackSpeedEnderiumHoe": 2.0,
  "attackDamageEnderiumPaxel": 20,
  "attackSpeedEnderiumPaxel": 2.0,
  "attackDamageEnderiumHammer": 20,
  "attackSpeedEnderiumHammer": 2.0,
  "attackDamageEnderiumExcavator": 20,
  "attackSpeedEnderiumExcavator": 2.0
}