{
  "toughnessValueVibraniumArmor": 100,
  "enchantmentValueVibraniumArmor": 85,
  "knockbackResistanceValueVibraniumArmor": 1,
  "protectionValueVibraniumBoots": 10,
  "protectionValueVibraniumLeggings": 15,
  "protectionValueVibraniumChestplate": 20,
  "protectionValueVibraniumHelmet": 10,
  "speedIVibraniumArmor": true,
  "jumpIVibraniumArmor": true,
  "nightVisionVibraniumArmor": true,
  "canWalkOnPowderedSnowVibranium": true,
  "speedVibraniumTier": 40,
  "enchantmentValueVibraniumBow": 5,
  "damageVibraniumBow": 8,
  "attackDamageBonusVibraniumTier": 11,
  "enchantmentValueVibraniumTier": 85,
  "attackDamageVibraniumPickaxe": 9,
  "attackSpeedVibraniumPickaxe": 2.0,
  "attackDamageVibraniumAxe": 10,
  "attackSpeedVibraniumAxe": 2.0,
  "attackDamageVibraniumShovel": 9,
  "attackSpeedVibraniumShovel": 2.0,
  "attackDamageVibraniumSword": 10,
  "attackSpeedVibraniumSword": 2.0,
  "attackDamageVibraniumHoe": 7,
  "attackSpeedVibraniumHoe": 2.0,
  "attackDamageVibraniumPaxel": 15,
  "attackSpeedVibraniumPaxel": 2.0,
  "attackDamageVibraniumHammer": 13,
  "attackSpeedVibraniumHammer": 2.0,
  "attackDamageVibraniumExcavator": 13,
  "attackSpeedVibraniumExcavator": 2.0
}