{
  "toughnessValueVulpusArmor": 150,
  "enchantmentValueVulpusArmor": 85,
  "knockbackResistanceValueVulpusArmor": 2,
  "protectionValueVulpusBoots": 20,
  "protectionValueVulpusLeggings": 25,
  "protectionValueVulpusChestplate": 35,
  "protectionValueVulpusHelmet": 20,
  "speedIIVulpusArmor": true,
  "jumpIIVulpusArmor": true,
  "nightVisionVulpusArmor": true,
  "fireResistanceVulpusArmor": true,
  "immuneToFallDamageVulpusArmor": true,
  "neverLoseHungerVulpusArmor": true,
  "canWalkOnPowderedSnowVulpus": true,
  "makesPiglinsNeutralVulpus": true,
  "speedVulpusTier": 75,
  "enchantmentValueVulpusBow": 5,
  "damageVulpusBow": 10,
  "attackDamageBonusVulpusTier": 20,
  "enchantmentValueVulpusTier": 85,
  "attackDamageVulpusPickaxe": 10,
  "attackSpeedVulpusPickaxe": 2.0,
  "attackDamageVulpusAxe": 15,
  "attackSpeedVulpusAxe": 2.0,
  "attackDamageVulpusShovel": 12,
  "attackSpeedVulpusShovel": 2.0,
  "attackDamageVulpusSword": 14,
  "attackSpeedVulpusSword": 2.0,
  "attackDamageVulpusHoe": 10,
  "attackSpeedVulpusHoe": 2.0,
  "attackDamageVulpusPaxel": 18,
  "attackSpeedVulpusPaxel": 2.0,
  "attackDamageVulpusHammer": 17,
  "attackSpeedVulpusHammer": 2.0,
  "attackDamageVulpusExcavator": 17,
  "attackSpeedVulpusExcavator": 2.0
}