[goggles]
enhancedInfo = true
hideStaticKineticInfo = true
enhancedStoreRender = true
renderExtraItems = true
enableKineticEffect = true
preciseNumbers = true
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[chainConveyor]
alwaysAllowRiding = false
preventFalling = false
enhancedConnection = true
cardBoardedYourself = false
[armor]
removeBoxOverlay = true
removeNetheriteFirstPerson = false
removeDivingBootsAffect = false
[wrench]
alwaysAllowRotating = true
removeCooldown = true
[other]
rainbowDebug = false
forcedBackend = false
nonrandomScrap = true
nbtFix = false
