version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
supplementaries = true
mutantmonsters = true
create_mechanical_extruder = true
valhelsia_structures = true
create_easy_structures = true
molten_vents = true
weeping_angels = true
create = true
easymagic = true
ribbits = true
createcasing = true
ironchest = true
friendsandfoes = true
gravestone = true
easyanvils = true
visualworkbench = true
sereneseasons = true
minecraft = true
cmr = true
comforts = true
regions_unexplored = true
fastpaintings = true
endermanoverhaul = true
duneons = true
amendments = true
creeperoverhaul = true
realmrpg_skeletons = true
immersiveores = true
ironfurnaces = true
chunkloaders = true
createsifter = true
enchantinginfuser = true
sophisticatedbackpacks = true
mobs_of_mythology = true
illagerinvasion = true
