# Don't change this! Version used to track needed updates.
version = 0
turnOffPotionParticles = "NONE"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
disableParticles = false

[byTypeReductions]
"minecraft:smoke" = 0.895424836601307