[spawn]
	#The minimum amount of 'Weeping Angels' that spawn at each spawn attempt
	# Default: 1
	# Range: 1 ~ 100
	minCount = 1
	#The maximum amount of 'Weeping Angels' that spawn at each spawn attempt
	# Default: 4
	# Range: 1 ~ 100
	maxCount = 4
	#The weight of spawn in relation to other mods 'Weeping Angels' will spawn in. Less than 100 = Rarer
	# Default: 8
	# Range: > 1
	spawn_weight = 8
	#'Weeping Angel' spawn classification
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT, MISC, GLARES, RASCALS
	spawnType = "MONSTER"
